#!/usr/bin/env perl

use strict;
use warnings;
use lib qw( lib );

use Pipework::Pipeline;
use Pipework::Message::MyDoc;

my $pipeline = Pipework::Pipeline->new( 'MyDoc' );

# same as Pipework::Stage::FetchURL->new( ... )
$pipeline->register( 'FetchURL' );
$pipeline->register( 'GetDocumentBody' );
$pipeline->register( sub {
	my $message = shift;

	warn( "body:\n" . $message->body );
} );

# same as Pipework::Message::MyDoc->new( ... )
my $message = $pipeline->message( {
	url => 'http://localhost/',
} );
my $result = $pipeline->process( $message );

