#!/usr/bin/env perl

use strict;
use warnings;
use lib qw( lib );

use Pipework::Line;
use Pipework::Message::MyDoc;

my $line = Pipework::Line->new( 'MyDoc' );

# same as Pipework::Stage::FetchURL->new( ... )
$line->register( 'FetchURL' );
$line->register( 'GetDocumentBody' );
$line->register( sub {
	my $message = shift;

	warn( "body:\n" . $message->body );
} );

# same as Pipework::Message::MyDoc->new( ... )
my $message = $line->message( {
	url => 'http://localhost/',
} );
my $result = $line->process( $message );

